---
title: 'Integration'
author: 'Maud Van Ginneken'
output:
  pdf_document:
    number_sections: yes
    keep_tex: yes
  html_document:
    df_print: paged
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = TRUE, autodep = TRUE, warning = FALSE, 
                      message = FALSE, echo = FALSE, eval = TRUE, tidy = TRUE,
                      fig.width = 6, fig.height = 3.5, purl = TRUE, 
                      fig.show = "hold", fig.pos = "p")
```

```{r}
remotes::install_github("mojaveazure/seurat-disk")
#library("Seurat")
#library("SeuratDisk")
```

```{r}
LJ_root <- LoadH5Seurat('/scratch/gent/472/vsc47291/MA1_CompPlantDev/preprocessing/LJ_root.h5Seurat')
```

```{r}
# Raw data gebruiken 
# Seurat object genereren 
# Normaliseren + scalen 

common_genes <- intersect(rownames(AT_root), rownames(LJ_root))

subset.matrix <- LJ_root@assays[["RNA"]]@counts[common_genes, ] # Pull the expression matrix from the original Seurat object containing only the genes of interest

LJ_root_ortho <- CreateSeuratObject(subset.matrix) # Create a new Seurat object with just the genes of interest

LJ_root_ortho <- NormalizeData(LJ_root_ortho)
all_genes_LJ <- rownames(LJ_root_ortho)
LJ_root_ortho <- ScaleData(LJ_root_ortho, features = all_genes_LJ)

#AddMetaData naar LJ_root, ploïdie uit LJ_root_ortho (Idents)
orig.ident <- AT_root@meta.data # Pull the identities from the original Seurat object as a data.frame

counts_AT_ <- as.matrix(AT_root@assays[["RNA"]]@layers[["counts"]])
rownames(counts_AT_) <- all_genes_AT

subset.matrix <- counts_AT_[common_genes, ] # Pull the expression matrix from the original Seurat object containing only the genes of interest

#subset.matrix <- AT_root@assays[["RNA"]]@counts[common_genes, ]

AT_root_ortho <- CreateSeuratObject(subset.matrix) # Create a new Seurat object with just the genes of interest

AT_root_ortho <- NormalizeData(AT_root_ortho)
all_genes_AT <- rownames(AT_root_ortho)
AT_root_ortho <- ScaleData(AT_root_ortho, features = all_genes_AT)

AT_root_ortho <- AddMetaData(object = AT_root_ortho, metadata = orig.ident) # Add the idents to the meta.data slot

Idents(object = AT_root_ortho) <- AT_root@active.ident # Assign identities for the new Seurat object
```

```{r}
#common_genes <- intersect(rownames(AT_root), rownames(LJ_root))
#AT_root <- AT_root[, common_genes]
#LJ_root <- LJ_root[, common_genes]
```

```{r}

```


```{r}
AT_anchors <- FindTransferAnchors(reference = AT_root, query = LJ_root_ortho, 
    dims = 1:30, features = common_genes, reduction = "pcaproject")
```

# Ploïdy
```{r}
predictions <- TransferData(anchorset = AT_anchors, refdata = AT_root$ploidy.ID.P, 
    dims = 1:30)
LJ_root_ortho <- AddMetaData(LJ_root_ortho, metadata = predictions)
```

```{r}
LJ_root <- AddMetaData(object = LJ_root, metadata = LJ_root_ortho@meta.data) 
Idents(object = LJ_root) <- LJ_root_ortho@meta.data[["predicted.id"]] 
```

```{r fig.height = 16 fig.width = 16}
#options(repr.plot.width=16, repr.plot.height=16)
order <- c("2C","4C","8C","16C","unknown")
palette <- c("#DCEDC8","#42B3D5","#FDEA6F","#CF4F29","#cccccc")

LJ_root$predicted.id <- factor(LJ_root$predicted.id, levels=order[sort(match(unique(LJ_root$predicted.id), order))])
color <- palette

ploidyplot <- DimPlot(LJ_root, group.by="predicted.id", cols=color, reduction = 'umap60', dims = c(1,2)) + labs(x = "", y = "", title = "Ploidy levels")

#pdf(file = "ploidyplot.pdf", width = 16, height = 16)
ploidyplot
#dev.off()
```

# Timezones 

```{r}
predictions <- TransferData(anchorset = AT_anchors, refdata = AT_root$timezone.ID.P, 
    dims = 1:30)
LJ_root_ortho <- AddMetaData(LJ_root_ortho, metadata = predictions)
```
```{r}
LJ_root <- AddMetaData(object = LJ_root, metadata = LJ_root_ortho@meta.data) 
Idents(object = LJ_root) <- LJ_root_ortho@meta.data[["predicted.id"]] 
```

```{r}
timezone <- DimPlot(LJ_root, reduction = "umap60", group.by = "predicted.id")+ggtitle("Correlation-based timezone annotation")

timezone
```

# Cell types 

```{r}
AT_root$celltype.id <- as.vector(AT_root@active.ident)
predictions <- TransferData(anchorset = AT_anchors, refdata = AT_root$celltype.id, 
    dims = 1:30)
LJ_root_ortho <- AddMetaData(LJ_root_ortho, metadata = predictions)
```

```{r}
LJ_root <- AddMetaData(object = LJ_root, metadata = LJ_root_ortho@meta.data) 
Idents(object = LJ_root) <- LJ_root_ortho@meta.data[["predicted.id"]] 
```

```{r}
celltype <- DimPlot(LJ_root, reduction = "umap60", group.by = "predicted.id")+ggtitle("Cell type annotation")

celltype
```

